alias dev-certs "security find-identity -v -p codesigning"
alias dns-flush "sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder; echo \"DNS has been flushed\""
alias dropbox "dropbox_uploader.sh"
alias finder "open ."
alias fix-open-with "/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user;killall Finder;echo \"Open With has been rebuilt, Finder will relaunch\""
alias fuxcode "rm -rf ~/Library/Developer/Xcode/DerivedData/"
alias git "gh"
alias gpg "gpg2"
alias osxinfo "sw_vers"
alias permission-fix "sudo chown -R (whoami):admin /usr/local"
alias rsa "cat ~/.ssh/id_rsa.pub | pbcopy"
alias ssh-server "ssh server.redalemeden.com"
alias subl "sublime ./"
alias tower "gittower ./"
alias xcode "open -a 'Xcode' ."
alias xcode-beta "open -a 'Xcode-Beta' ."

