alias debian-droplet "ssh ssh-debian.redalemeden.com"
alias finder "open ."
alias osxinfo "sw_vers"
alias rsa "cat ~/.ssh/id_rsa.pub | pbcopy"
alias subl "sublime ./"
alias tower "gittower ./"
alias xcode "open -a 'Xcode' ."
alias fuxcode "rm -rf ~/Library/Developer/Xcode/DerivedData/"
alias dns-flush "sudo discoveryutil udnsflushcaches"
