alias certs "security find-identity -v -p codesigning"
alias dns-flush "sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder; echo \"DNS has been flushed\""
alias dockcomp "docker-compose"
alias dockcont "docker container"
alias finder "open ."
alias killpid "kill -13"
alias mkdir "mkdir -p"
alias osxinfo "sw_vers"
alias port "lsof -i"
alias ports "lsof -nP +c 15 | grep LISTEN"
alias python "python3"
alias vim "nvim"
alias xcode "open -a 'Xcode' ."
alias xcode-b "open -a 'Xcode-beta' ."
alias swiftc-wasm "/Library/Developer/Toolchains/swift-wasm-5.9.1-RELEASE.xctoolchain/usr/bin/swiftc"
