set shell=bash

if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/bundle/neobundle.vim/
end

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch "Shougo/neobundle.vim"
NeoBundle "dag/vim-fish"
NeoBundle "elzr/vim-json"
NeoBundle "ekalinin/Dockerfile.vim"
NeoBundle "scrooloose/nerdtree"
call neobundle#end()
NeoBundleCheck

filetype plugin indent on
syntax on
highlight Normal ctermbg=none
highlight SignColumn ctermbg=none
highlight LineNr ctermbg=none ctermfg=62

" #NERDTree
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
map <C-n> :NERDTreeToggle<CR>

set laststatus=2
set noshowmode
set mouse=""
set hlsearch

set nobackup
set nowritebackup
set noswapfile

set backspace=2
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

set splitbelow
set splitright

set number
set numberwidth=5

imap <c-a> <esc>
vmap <c-a> <esc>
nmap <return> :

imap jk <esc>
imap kj <esc>
imap jj <esc>
imap kk <esc>

nmap <c-h> <c-w>h
nmap <c-j> <c-w>j
nmap <c-k> <c-w>k
nmap <c-l> <c-w>l

nmap <c-q> <c-w>-
nmap <c-a> <c-w>>
nmap <c-s> <c-w><
nmap <c-z> <c-w>+

nmap <leader>r :vsp $MYVIMRC<cr>
nmap <leader>b :sp<cr>
nmap <leader>v :vsp<cr>
nmap <leader>s :w<cr>

nnoremap <left> :echoe "use h"<cr>
nnoremap <right> :echoe "use l"<cr>
nnoremap <up> :echoe "use k"<cr>
nnoremap <down> :echoe "use j"<cr>
