set shell=bash

if has('vim_starting')
  set nocompatible
  set runtimepath+=~/.vim/bundle/neobundle.vim/
end

call neobundle#begin(expand('~/.vim/bundle/'))
NeoBundleFetch "Shougo/neobundle.vim"
NeoBundle "bling/vim-airline"
NeoBundle "dag/vim-fish"
NeoBundle "elzr/vim-json"
NeoBundle "ekalinin/Dockerfile.vim"
call neobundle#end()
NeoBundleCheck

filetype plugin indent on
syntax on
colorscheme tomorrow-night

autocmd BufRead,BufNewFile Vagrantfile set filetype=ruby
autocmd BufRead,BufNewFile Berksfile set filetype=ruby

set laststatus=2
set noshowmode
set mouse=""
set hlsearch

set nobackup
set nowritebackup
set noswapfile

set backspace=2
set tabstop=2
set shiftwidth=2
set shiftround
set expandtab

set splitbelow
set splitright

set number
set numberwidth=5

set cursorline

imap <c-a> <esc>
vmap <c-a> <esc>
nmap <return> :

imap jk <esc>
imap kj <esc>
imap jj <esc>
imap kk <esc>

nmap <c-h> <c-w>h
nmap <c-j> <c-w>j
nmap <c-k> <c-w>k
nmap <c-l> <c-w>l

nmap <c-q> <c-w>-
nmap <c-a> <c-w>>
nmap <c-s> <c-w><
nmap <c-z> <c-w>+

nmap <leader>r :vsp $MYVIMRC<cr>
nmap <leader>b :sp<cr>
nmap <leader>v :vsp<cr>
nmap <leader>s :w<cr>

nnoremap <left> :echoe "use h"<cr>
nnoremap <right> :echoe "use l"<cr>
nnoremap <up> :echoe "use k"<cr>
nnoremap <down> :echoe "use j"<cr>

let g:airline_theme='night'
let g:airline_section_a = "%{tolower(airline#util#wrap(airline#parts#mode(),0))}"
let g:airline_section_b = "\u27E9 %F"
let g:airline_section_y = "%p%% \u27E8 %{airline#util#wrap(airline#parts#filetype(),0)}"
let g:airline_section_c = ""
let g:airline_section_x = ""
let g:airline_section_z = ""
let g:airline_left_sep = ""
let g:airline_right_sep = ""

let g:netrw_liststyle = 3
let g:netrw_banner = 0
let g:netrw_browse_split = 4
let g:netrw_winsize = 20
let g:netrw_altv = 1
