alias ... "cd ../.."
alias ls "ls -al"
alias mkdir "mkdir -p"
alias rm "rm -rf"
alias port "lsof -i"
alias killpid "kill -9"
alias gitc "git aa | git c"
alias dockcont "docker container"
alias dockcomp "docker-compose"

