alias migrate 'rake db:migrate'
alias parallel-spec 'bundle exec rake parallel:spec'
alias mkdir 'mkdir -p'
alias ... '../..'
alias aliases 'mvim ~/.config/fish/aliases.fish'
alias sshnfs 'ssh kaishin_kaishinlab@ssh.phx.nearlyfreespeech.net'
alias rsync '/usr/local/bin/rsync'
alias tower 'gittower'
alias fixopenwith '/System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/Support/lsregister -kill -r -domain local -domain user'
alias unfollow 't leaders | xargs t unfollow >/dev/null'
alias xcode "open -a 'Xcode' ."
alias bower 'bower'
alias pow 'powder'
alias gs 'gitsh --git (which gh)'
alias git 'gh'
alias rsa 'cat ~/.ssh/id_rsa.pub | pbcopy'
alias flatten 'mv -n ./*/* . & find . -maxdepth 1 -empty -type d -exec rm -rf \{\} \;> /dev/null'
alias finder 'open .'
alias restart-pg 'launchctl unload ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist & launchctl load ~/Library/LaunchAgents/homebrew.mxcl.postgresql.plist'
