alias migrate "rake db:migrate"
alias mkdir "mkdir -p"
alias ... "../.."
alias aliases "mvim ~/.config/fish/aliases.fish"
alias gco "git checkout"
alias ghb "hub browse"
alias ghco "hub checkout"
alias gmt "git mergetool"
alias gpf "git push -f"
alias gpl "git pull --rebase"
alias gpr "hub pull-request"
alias gra "git rebase --abort"
alias grc "git rebase --continue"
alias grim "git rebase -i master"
alias grm "git rebase master"
alias sshnfs "ssh kaishin_kaishinlab@ssh.phx.nearlyfreespeech.net"
alias rsync "/usr/local/bin/rsync"
alias tower "gittower"
alias fixopenwith '/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user'
alias unfollow "t leaders | xargs t unfollow >/dev/null"
alias oculair "cd ~/Developer/iOS/oculair | xcode | gitsh"
alias verbena "cd ~/Developer/iOS/Verbena | xcode"
alias ios-playground "cd ~/Developer/iOS/Playground | xcode"
alias neat-repo "cd ~/Developer/libs/neat"
alias xcode "open -a 'Xcode' ."
alias kaishinlab "cd ~/Developer/web/kaishinlab"
alias bower 'bower'
alias pow 'powder'
alias rsa 'cat ~/.ssh/id_rsa.pub | pbcopy'
